-- AlterEnum: Add CANDIDATE_DOCUMENT_VIEWED and SECURITY_ALERT_INVALID_STORAGE_PATH to AuditAction
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'CANDIDATE_DOCUMENT_VIEWED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SECURITY_ALERT_INVALID_STORAGE_PATH';
